name: Lint and Test
on:
  push:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    name: lint and test
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npm run test